### PR TITLE
Documented permessage-deflate

### PR DESCRIPTION
**Pull request by nkzawa**
Add descriptions of permessage-deflate.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Thanks for the pull request. Given the amount of pull requests you've made? Would you like to have full push access to the websockets/* projects?

**Comment by nkzawa** [comment]
Yeah, it would be helpful.

**Comment by nkzawa** [comment]
Thanks for inviting me :D

**Comment by 3rd-Eden** [comment]
Yeah, sorry for the long wait I was/am traveling to and in US atm so I have limited access to internet and time in general.

**Pull request merged**
