### PR TITLE
Allow socket to be passed through options.

### PR DESCRIPTION
**Pull request by bacek**
This will allow http proxy support via establishing connection upfront.

This is revived version of PR #514. Example of usage:

``` js
connectViaProxy(endpoint) {
        return new Promise((resolve, reject) => {
            const proxyUrl = url.parse(process.env.http_proxy);
            const endpointUrl = url.parse(endpoint);

            var options = {
                port: parseInt(proxyUrl.port),
                hostname: proxyUrl.hostname,
                method: "CONNECT",
                path: endpointUrl.hostname + ":" + (endpointUrl.port || 443),
            };

            this.logger.debug(`Proxy options ${util.inspect(options)}`);

            var req = http.request(options);

            req.on("connect", (res, socket, head) => {
                console.log("Connected via proxy");
                resolve(socket);
            });

            req.on("error", err => {
                console.error("Error connecting to proxy",  {err});
                reject(err);
            });

            req.end();
}

connectViaProxy(endpoint).then(socket => {
     new WebSocket(endpoint, {socket: socket});
});
```

### CODE REVIEW

**Comment by lpinca** [comment]
It seems that [`http.request()`](https://nodejs.org/api/http.html#http_http_request_options_callback) does not accept a `socket` option.
Am I missing something?

**Comment by bacek** [comment]
I'm not sure about documentation, but it does work as expected.

There is my log with NODE_DEBUG=net
```
19/10/2016, 9:47:14 AM INFO [VoiceSender@session.ts:36:21] Connecting to VoiceService
19/10/2016, 9:47:14 AM INFO [session.ts:73:25] Connecting to wss://..../ via proxy http://localhost:3128/
19/10/2016, 9:47:14 AM DEBUG [session.ts:84:25] Proxy options { port: 3128,
  hostname: 'localhost',
  method: 'CONNECT',
  path: '...:443' }
NET 8570: createConnection [ { host: 'localhost',
    port: 3128,
    hostname: 'localhost',
    method: 'CONNECT',
    path: null,
    servername: 'localhost',
    _agentKey: 'localhost:3128:',
    encoding: null } ]
NET 8570: pipe false null
NET 8570: connect: find host localhost
NET 8570: connect: dns options { family: undefined, hints: 40 }
NET 8570: _read
NET 8570: _read wait for connection
NET 8570: afterShutdown destroyed=true ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: false,
  endEmitted: false,
  reading: true,
  sync: false,
  needReadable: true,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 8570: emit close
NET 8570: afterConnect
NET 8570: _read
NET 8570: Socket._read readStart
NET 8570: onread 39
NET 8570: got data
19/10/2016, 9:47:14 AM DEBUG [session.ts:89:29] Connected via proxy
NET 8570: _read
19/10/2016, 9:47:14 AM INFO [session.ts:40:25] Got socket [object Object]
NET 8570: _read
NET 8570: afterWrite 0
NET 8570: afterWrite call cb
NET 8570: onread 233
NET 8570: got data
19/10/2016, 9:47:14 AM INFO [session.ts:43:29] Connected to VoiceService
NET 8570: _read
NET 8570: afterWrite 0
NET 8570: afterWrite call cb
NET 8570: onread 48363
NET 8570: got data
NET 8570: _read
19/10/2016, 9:47:16 AM DEBUG [session.ts:219:29] [1] SPOTTED
19/10/2016, 9:47:16 AM INFO [session.ts:229:25] Creating VoiceSender 
NET 8570: onread 27025
NET 8570: got data
NET 8570: _read
NET 8570: afterWrite 0
NET 8570: afterWrite call cb
NET 8570: onread 43
NET 8570: got data
NET 8570: _read
19/10/2016, 9:47:17 AM DEBUG [onVoiceMessage@session.ts:251:21] [1] onVoiceMessage {"command":"recogniser_connected"}

```

**Comment by lpinca** [comment]
@bacek I tried to look into [`http.clientRequest`](https://github.com/nodejs/node/blob/92ece8671a3da8910bc8755b16ac121ba300a122/lib/_http_client.js) to see if the `socket` option was undocumented but I couldn't find it so I tried with something very similar to your example:

```js
'use strict';

const http = require('http');
const net = require('net');

const WebSocket = require('.');

const proxy = http.createServer();

proxy.on('connect', (request, clientSocket) => {
  const serverSocket = net.connect(80, 'echo.websocket.org', () => {
    clientSocket.write(
      'HTTP/1.1 200 OK\r\n' +
      'Proxy-agent: Node.js\r\n' +
      '\r\n'
    );

    serverSocket.pipe(clientSocket);
    clientSocket.on('data', (data) => {
      console.log(data.toString());
      serverSocket.write(data);
    });
  });
});

proxy.listen(() => {
  const request = http.request({
    port: proxy.address().port,
    hostname: 'localhost',
    method: 'CONNECT'
  });

  request.on('connect', (response, socket) => {
    console.log(`${response.statusCode} ${response.statusMessage}`);

    const ws = new WebSocket('ws://echo.websocket.org', { socket });

    ws.on('message', (msg) => console.log(msg));
    ws.on('open', () => ws.send('hello'));
  });

  request.end();
});
```

There is no activity on `clientSocket` so I doubt it works as intended unless I'm still missing something.

**Comment by bacek** [comment]
Hello.

Your example is slightly different. Can you try to pass ```{ socket: socket
}``` to WebSocket constructor?

**Comment by lpinca** [comment]
@bacek `{ socket }` is just a shortcut for ` { socket: socket }` but I tried changing it to the latter and it doesn't make any difference.

**Comment by lpinca** [comment]
Closing this in favor of https://github.com/TooTallNate/node-https-proxy-agent or similar alternatives.

Thanks.

**Pull request closed without merging**
