### PR TITLE
Status code must be 1006 if the socket is closed without having recei…

### PR DESCRIPTION
**Pull request by jondubois**
…ved a close control frame

### CODE REVIEW

**Comment by jtblin** [comment]
Works like a charm!

**Comment by jtblin** [comment]
Any ETA to get this merged in please?

**Comment by jondubois** [comment]
@jtblin I made a temporary fork which I'm currently using for my own project - If this fix is important to your case, you can use it in the meantime: https://www.npmjs.com/package/sc-ws - I guess the merge/release cycle for ws is slow because of the sheer number of dependants.

**Comment by polomsky** [comment]
:+1:

**Comment by 3rd-Eden** [comment]
Thanks for the contribution, will be availabe in the next 1.0 release

**Pull request merged**
