### PR TITLE
Fix issue with server not releasing port

### PR DESCRIPTION
**Pull request by woverton**
Please see https://github.com/websockets/ws/issues/527 for the discussion about this issue.

Let me know if you need anything.

### CODE REVIEW

**Comment by Gray1989** [comment]
You don't need to rewrite it like you did. These changes would work fine:

```javascript
this._closeServer = function(cb) { self._server?self._server.close(cb):cb(); };

WebSocketServer.prototype.close = function(cb) {
  // terminate all associated clients
  var error = null;
  try {
    for (var i = 0, l = this.clients.length; i < l; ++i) {
      this.clients[i].terminate();
    }
  }
  catch (e) {
    error = e;
  }

  // remove path descriptor, if any
  if (this.path && this._server._webSocketPaths) {
    delete this._server._webSocketPaths[this.path];
    if (Object.keys(this._server._webSocketPaths).length == 0) {
      delete this._server._webSocketPaths;
    }
  }

  // close the http server if it was internally created
  try {
    if (typeof this._closeServer !== 'undefined') // checking if it matches the string "undefined", possible logic error?
      this._closeServer(cb);
    else if(cb !== undefined) cb();
  }
  finally {
    delete this._server;
  }
  if (error) throw error;
}
```

Ignoring the possible logic error already implemented... The if/else was simply shortened and the callback was passed as-is through to the method. Also not sure why you created the closure for simply calling the method and deleting the _server object. Not deleting the _server object when it was originally designed to be deleted could lead to more logic errors further on in the application or in the way people use it so it's always best to try to change as little as possible. Adding functionality is always good but changing the way things work needs to be done with extreme caution.

**Comment by woverton** [comment]
Yeah you're right. I should have remade my fix after the time I spent tracking it down. Finding the fix took a little longer than it should have. Feel free to drop this and create a PR with your fix in.

**Comment by rimmartin** [comment]
Hi,

Since this was in conflict with current master branch I tried applying @Gray1989 but now thee callback gets called twice because another callback was put in at:
https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L156

Best way around this?  and I'd like to see it get pulled in to the master

**Comment by lpinca** [comment]
Closing as this should be addressed in master.

**Pull request closed without merging**
