### PR TITLE
wscat: Support sending control frames (ping, pong, close)

### PR DESCRIPTION
**Pull request by simonratner**
Commands are prefixed with a slash "/" character.  The remainder of the
input line is used as command parameters. Also, print out ping and pong
control frames when they are received.

Example:

```
$ ./bin/wscat -c ws://echo.websocket.org
connected (press CTRL+C to quit)
> hi there
< hi there
> /ping
pong
> /ping echo
pong echo
> /close 1001 bye
disconnected
```

### CODE REVIEW

**Comment by lpinca** [comment]
`wscat` has moved to https://github.com/websockets/wscat. Can you please resubmit there?
Thank you.

**Comment by simonratner** [comment]
It has been a while. I no longer use this library, nor do I have an OSX machine handy to verify that the patch still works.

Feel free to take this code verbatim, or modify and merge as needed, if you think this functionality should be in https://github.com/websockets/wscat.

**Comment by lpinca** [comment]
cc: @nwwells who is helping maintaining `wscat`.

**Comment by nwwells** [comment]
We'll track this on websockets/wscat#32. @lpinca you can close this if you want, and I'll just reference the commits from there.

**Pull request closed without merging**
