### PR TITLE
Pass localAddress option to http request object.

### PR DESCRIPTION
**Pull request by aklaswad**
Hi

I know this doesn't have major usage, but I found that there is no way to specify which network interface ws would use, during I've been trying to compare the responsibility of multiple networks. Am happy if you consider to merge this change. thanks!

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Would be nice to have test against this.

**Comment by aklaswad** [comment]
added some simple test, and fixed a bug.

**Comment by aklaswad** [comment]
Grr, looks the test doesn't work on travis-ci, though it's fine for my osx.
And each versions of nodejs are throwing different exception...

**Comment by 3rd-Eden** [comment]
Thanks for your contribution

**Pull request merged**
