### PR TITLE
Avoiding memory leaks

### PR DESCRIPTION
**Pull request by andrija-hers**
Here is a massive refactor that minimizes memory leaks.

There are 2 important notes here:
1. This PR will not work until https://github.com/einaros/options.js/pull/14 is accepted (the `options` module leaks memory massively)
2. One of the test still fails - just like the original code does (due to timeout of 5000 ms)

I hope that @einaros will take care of the `options` repo so that this PR may be accepted.

The code changes are pretty much self explanatory, but I'll just note that almost all the work is based on removing the notorious `var self = this` paradigm, that _always_ leads to memory leaks (via closures that never get collected as garbage).

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Might make more sense to dump the options module completely.

**Comment by 3rd-Eden** [comment]
As for the `var self = this` -- We're changing to fat arrow syntax so that should be resolved in master.

**Comment by einaros** [comment]
Regarding the Options pullreq, I can accept it, but at first glance it seems unnecessary. When references to an Options instance are released, everything - including the closures - should be gc'd.

**Comment by JacksonTian** [comment]
@andrija-hers could you rebase it with master

**Comment by andrija-hers** [comment]
@JacksonTian I'll do my best, asap

**Comment by lpinca** [comment]
Is this still needed? We no longer depend on `options` and are no longer using the `var self = this;` paradigm.

**Comment by lpinca** [comment]
I'm going to close this as there would be a pretty big amount of work only to rebase against master.
Thanks a lot for the effort you put here @andrija-hers.

**Pull request closed without merging**
