### PR TITLE
Indicate optional params in JSDoc

### PR DESCRIPTION
**Pull request by Jokero**
To avoid warnings in IDE:
image

### CODE REVIEW

**Comment by lpinca** [comment]
I'm not very happy with this because:

1. AFAIK there is no proper way to define the position of an optional arguments. For example in the `websocket.close([code[, reason]])` signature `reason` is optional but if specified it must be the second argument.
1. If we do this we should do it everywhere and not only in a couple of files.

**Comment by Jokero** [comment]
1. I actually always thought that order of optional parameters is strict and if some function has such description
```js
/**
 * @param {number} [a]
 * @param {string} [b]
 * @param {boolean} [c]
 */
function test(a, b, c) {}
```
it can be used only this way
```js
test(1);
test(1, 'b');
test(1, 'b', true);
```
I wouldn't expect this will be correct
```js
test('b');
```
But I can't find any proof or disproof, jsdoc spec is quite poor on examples and comments

2. Maybe. But small improvements are still improvements

**Comment by lpinca** [comment]
Assume that in your example the `a` argument is defined as `@param {string} [a]`. `test('b')` would then be correct.

**Comment by lpinca** [comment]
Anyway if you want to get this merged, please do it for all files. It shouldn't take a lot of time and I can help if needed.

Thank you.

**Comment by Jokero** [comment]
> test('b') would then be correct if b can be used as first argument when a is not provided.

I would never allow in real code to skip arguments as it's so not obvious and only confuses.

Ok, if you are not against these changes, I'll try to do it in all files

**Comment by lpinca** [comment]
@Jokero are you interested in finishing this off?

**Comment by Jokero** [comment]
I can try to finish it next week

**Comment by lpinca** [comment]
@Jokero I went ahead and finished it, I hope you don't mind.

**Comment by lpinca** [comment]
Thank you.

**Comment by Jokero** [comment]
I don't mind 😄 Thanks for your work

**Pull request merged**
