### PR TITLE
Fixed invalid object in example.

### PR DESCRIPTION
**Pull request by oxygens**

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Works as intended, it's ES6 syntax.

**Comment by oxygens** [comment]
Well it didn't work for me in node 7.8 which supports ES6 syntax out of the box.

**Comment by 3rd-Eden** [comment]
```js
 node                                                                                                                                                                              ~/Projects/ux/ux-charts 1 ↵
> console.log(process.versions);
{ http_parser: '2.7.0',
  node: '7.5.0',
  v8: '5.4.500.48',
  uv: '1.10.2',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
undefined
> const server = 'foo';
undefined
> const example = { server };
undefined
> console.log(example);
{ server: 'foo' }
undefined
>
```

Node 7.8 repl output.

**Comment by oxygens** [comment]
Actually it didn't work in babel or webpack (I'm using the most I can out of ES7). 

Sorry for the confusion.

**Comment by oxygens** [comment]
Can't remember what I did then.

I would still make the docs clearer though :)

**Pull request closed without merging**
