### PR TITLE
Add comments documenting things that may not be obvious to noobs :)

### PR DESCRIPTION
**Pull request by earthbound19**
Subject describes changes.

### CODE REVIEW

**Comment by lpinca** [comment]
Hmm I'm not too happy with these changes. The installation instructions can makes sense but the code comments seem redundant to me.

**Comment by lpinca** [comment]
@earthbound19 how about adding 2 README.md one for each example (fileapi and serverstats) in their respective folder and specify how to install the dependencies and run the example?

**Comment by earthbound19** [comment]
I can look at that. First time doing a pull request--would I just make those changes and issue a new request?

**Comment by lpinca** [comment]
@earthbound19 you can make the changes and force push to your doc branch.

**Comment by lpinca** [comment]
Actually there is no need to force push. You can just add more commit to you `doc` branch. I'll squash them when merging.

**Comment by earthbound19** [comment]
Ok. When I get to it and get your review. thx

**Comment by lpinca** [comment]
@earthbound19 any update on this?

**Comment by earthbound19** [comment]
Nope. I may not get to it. Frankly I think redundant as they may be, any noob would prefer the comments over nothing.

**Comment by lpinca** [comment]
Ok then I'll close this, sorry. The added comments are for people who are getting started with JavaScript/Node.js and have no place here.

I hope you'll find another way to contribute.

Thanks anyway!

**Pull request closed without merging**
