### PR TITLE
Added ExpressJS session parsing example to README

### PR DESCRIPTION
**Pull request by karatheodory**
Please find the related issue: #326

### CODE REVIEW

**Comment by JacksonTian** [comment]
@karatheodory the coding style should be keep consistent.

**Comment by lpinca** [comment]
I think it would be better to turn this into an example and put it in the examples folder.
@karatheodory are you up for doing that?

**Comment by karatheodory** [comment]
Yes, good idea, will do.

**Comment by karatheodory** [comment]
Created new pull request: https://github.com/websockets/ws/pull/1003

**Pull request closed without merging**
