### PR TITLE
Added support to send JSON Objects

### PR DESCRIPTION
**Pull request by piyushkantm**
This reduces repetition for backend dealing with JSON objects and makes the code elegant as we do not have to repeatedly use JSON.stringify everywhere..

### CODE REVIEW

**Comment by piyushkantm** [comment]
@lpinca I am not sure if i need to cover this change with tests too. Please suggest

**Comment by lpinca** [comment]
Thank you for the PR but this is not something that should be in ws.
It can easily be done outside of ws with a dead simple function.

```js
function sendJSON(ws, data, options, callback) {
  ws.send(JSON.stringify(data), options, callback);
}
```

**Comment by piyushkantm** [comment]
Ok, i get it. Thanks for your prompt reply.

**Comment by JayBeavers** [comment]
Disagree, nodejs lives & breathes JSON and there's easy ways to disambiguate an object from a string and auto-call JSON.stringify.

As a new user of this library, was quite surprised it didn't do this automatically when you sister libraries, like expressjs, handle this elegantly by default.

**Pull request closed without merging**
