### PR TITLE
expose close callback

### PR DESCRIPTION
**Pull request by coolaj86**

### CODE REVIEW

**Comment by Eeems** [comment]
Looks like pull request #611 provides this solution.

**Comment by nathanboktae** [comment]
No #611 is for a close callback on `WebSocketServer`. This is for one on `WebSocket`.

I'd love to see this PR. It's really odd that an asynchronous operation does not have a callback. There is no way to wait on the close of the socket. @coolaj86 could you fix the tests?

**Comment by Eeems** [comment]
You are correct, didn't look closely enough it seems.

**Comment by lpinca** [comment]
This should be rebased and handle cases where `readyState` is `CLOSED`, `CONNECTING` or `CLOSING`.

**Comment by lpinca** [comment]
Closing for now, please reopen if still interested.

**Pull request closed without merging**
