### PR TITLE
Move `completeUpgrade` to `WebSocketServer.prototype`

### PR DESCRIPTION
**Pull request by lpinca**
This brings the following changes:

- Merge the `upgrade` function into `WebSocketServer.prototype.handleUpgrade()`.
- Extract `completeUpgrade` from `upgrade` and add it to `WebSocketServer.prototype`.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Things are breaking :9

**Comment by lpinca** [comment]
It's coveralls which is drunk, tests pass :)

**Comment by 3rd-Eden** [comment]
@lpinca Yeah, I guess it complains when coverage gets reduced somehow.

**Comment by lpinca** [comment]
master branch (before merge)

```
=============================== Coverage summary ===============================
Statements   : 91.52% ( 1111/1214 )
Branches     : 88.75% ( 686/773 )
Functions    : 95.92% ( 94/98 )
Lines        : 92.4% ( 1045/1131 )
================================================================================
```

this branch

```
================================ Coverage summary ===============================
Statements   : 91.49% ( 1108/1211 )
Branches     : 88.72% ( 684/771 )
Functions    : 95.92% ( 94/98 )
Lines        : 92.37% ( 1041/1127 )
================================================================================
```

kinda weird as coverage is exactly the same.

**Comment by 3rd-Eden** [comment]
Well, the statements, branches and lines have less coverage in this branch.

**Comment by 3rd-Eden** [comment]
But what ever, it's not that important.

**Comment by lpinca** [comment]
If you compare it with the _total_ statements it's the same.

**Pull request merged**
