### PR TITLE
Add headers as option to verifyClient

### PR DESCRIPTION
**Pull request by mkamioner**
This allows the verifyClient to be more flexible in what it returns to the client if there is a failure on authentication. i.e. a retry-after etc.

Happy to hear feedback :-)

### CODE REVIEW

**Comment by mkamioner** [comment]
Couldn't find a way to conduct a test on the case where the test passed and check the header response...

**Comment by MeirionHughes** [comment]
Could this be updated and reviewed please? Seems like a rather important feature.

**Comment by lpinca** [comment]
@mkamioner can you please rebase against master?
Thanks.

**Comment by mkamioner** [comment]
@lpinca - I would be happy to do so! It might take a little bit of time though - hopefully I can it done by end of week

**Comment by lpinca** [comment]
@mkamioner sure, take your time!

**Comment by mirik123** [comment]
This is really great pull request. Please update typings repository as well.

**Comment by lpinca** [comment]
@mkamioner ping.

**Comment by lpinca** [comment]
Closing this, if anyone is interested please open a new PR.

**Comment by jlaine** [comment]
If anyone is wondering : this PR is required to be able to use Basic Authentication. As things stand, it is not possible to add a WWW-Authenticate header to the upgrade response, so the browser just gives up.

**Pull request closed without merging**
