### PR TITLE
Add ability to bind to specific interface 

### PR DESCRIPTION
**Pull request by psinghsp**
We have our software running on a machine with multiple network cards. Websocket connections can only be made (due to routing table set up) if the connection attempt is made from a specific interface. Node.js HTTP module has a property called "localAddress". Websocket module uses that - but does not pass this property to underlying HTTP module.

This pull request is basically 2-3 lines of code to allow a websocket client to provide a localAddress to bind to when creating a websocket.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Can't merge it in with all changes and lack of tests, sorry.

**Comment by psinghsp** [comment]
Change is 2 lines - so it should not have conflicts. If there are any other changes, I can resolve conflicts.

I can add tests as well.

**Comment by aklaswad** [comment]
look this is dupe of #551

**Comment by lpinca** [comment]
Closing this as duplicate of #551.

**Pull request closed without merging**
