### PR TITLE
Add ability to specify the masking key

### PR DESCRIPTION
**Pull request by lpinca**
Refs: https://github.com/websockets/ws/pull/1986
Refs: https://github.com/websockets/ws/pull/1988

### CODE REVIEW

**Comment by lpinca** [comment]
cc: @ronag @e3dio

**Review by ronag — APPROVED** [review]

**Comment by lpinca** [comment]
There are two issues with this

1. There is no way to provide a masking key for `ws.close()`.
2. The user provided masking key is not copied. If data is buffered and the user mutates the `Buffer`'s contents, then the masking key might not be the expected one. For example:

    ```js
    const mask = Buffer.alloc(4);

    mask.fill('a');

    ws.send(message, { mask });

    mask.fill('b');

    ws.send(message, { mask });

    mask.fill('b');
    ```

    In this case, all buffered messages will be masked with the same masking key. I'm not sure if it is better to document this or  copy the user provided key. What do you think?

**Comment by lpinca** [comment]
Another possible alternative, which might be simpler, could be a `randomMask` option on `WebSocket` constructor. The option specifies a user provided function to fill the mask buffer.

**Comment by ronag** [comment]
I think copying should also be fine. It’s 4 bytes.

**Comment by alexhultman** [comment]
> I think copying should also be fine. It’s 4 bytes.

Hehe, yes. A reference is **at least** 8 bytes so a copy is definitely fine.

**Comment by e3dio** [comment]
I would not want to require adding mask details to all my ws.send() calls individually, a `new WebSocket(url, { options })` mask option would be better, a function that takes the mask buffer as parameter would be good:
```javascript
const ws = new WebSocket(url, {
  maskBuffer(buf) {
    require('crypto').randomFillSync(buf, 0, 4) // default function
  }
})

const ws = new WebSocket(url, {
  maskBuffer(buf) {
    buf.writeUInt32BE(Math.random()*2**32) // Math.random example
  }
})

const ws = new WebSocket(url, {
  maskBuffer(buf) {
    buf.fill(0) // clear mask example
  }
})
```
Any ws.send() calls with a mask specified could override the maskBuffer function

**Comment by ronag** [comment]
I’m good with either option.

**Comment by e3dio** [comment]
FYI @alexhultman added clear mask checking on already optimized uWS server https://github.com/uNetworking/uWebSockets/commit/0c8be4d20ccce75be632dd8aae109b68485ccb40 and is reporting 10% performance improvement for large messages which is pretty good so it's ready and compatible with this PR, and you will probably see better improvement for this Node client which currently does crypto and bit xor

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/1990.

**Comment by lpinca** [comment]
Closing in favor of #1990.

**Pull request closed without merging**
