### PR TITLE
Change `Sender.prototype.frameAndSend()` signature

### PR DESCRIPTION
**Pull request by lpinca**
This updates the signature of the `frameAndSend` method to make it accept an options object.
This should make it easier to add more options in future without having to add more arguments and remember their position.

### CODE REVIEW

**Comment by lpinca** [comment]
@websockets/admin LGTY?

**Comment by Nibbler999** [comment]
You should also update the sender benchmark with the new signature.

**Comment by lpinca** [comment]
Oh right, thanks for pointing that out, on my way.

**Comment by lpinca** [comment]
I'll merge this later today if there are no objections.

**Pull request merged**
