### PR TITLE
Fix an error on Node v0.8 (no 'close' method for InflateRaw/DeflateRaw)

### PR DESCRIPTION
**Pull request by darrachequesne**

### CODE REVIEW

**Comment by darrachequesne** [comment]
@3rd-Eden hi! could you merge this please? It should fix the build on node v0.8, and prevent @rauchg from killing me.

**Comment by rauchg** [comment]
Haha no worries! I added a check for `process.version` to not have this happen to anyone. Still a great fix. Thank you @darrachequesne

**Comment by 3rd-Eden** [comment]
TY

**Comment by darrachequesne** [comment]
Great, thanks!

**Pull request merged**
