### PR TITLE
Minor tweaks to tests for robustness

### PR DESCRIPTION
**Pull request by infinity0**
- Allow use of a custom/system installation of mocha for tests
- Use higher ports for tests, less likely to conflict with actual services

### CODE REVIEW

**Comment by infinity0** [comment]
The tests are passing on node 4 and 5, fail on node 0.12 for some reason. Possibly node 0.12 is using ports 58000-5800x? The ideal solution would be to pick a port dynamically.

**Comment by 3rd-Eden** [comment]
It makes no sense to merge this if starts breaking test suite for no reason, while the current test suite and ports work just fine.

**Comment by infinity0** [comment]
It *doesn't* work fine on certain setups, i.e. if you have a service running on port 8008 already (e.g. Apple CalendarServer). I was going to re-patch it to use port 48008 instead of 58008 but had better things to do in the meantime.

**Comment by lpinca** [comment]
Closing this as we dropped support for Node.js < 4.

**Pull request closed without merging**
